#ifndef OM_LOG_H
#define OM_LOG_H

#define OPENCOINEVO_LOG_CATEGORY "OM"

#define OMINFO  CLOG(INFO, OPENCOINEVO_LOG_CATEGORY)
#define OMWARN  CLOG(WARNING, OPENCOINEVO_LOG_CATEGORY)
#define OMERROR CLOG(ERROR, OPENCOINEVO_LOG_CATEGORY)

#define OMVLOG1  CVLOG(1, OPENCOINEVO_LOG_CATEGORY)
#define OMVLOG2  CVLOG(2, OPENCOINEVO_LOG_CATEGORY)
#define OMVLOG3  CVLOG(3, OPENCOINEVO_LOG_CATEGORY)
#define OMVLOG4  CVLOG(4, OPENCOINEVO_LOG_CATEGORY)

#define OMINFO_IF(cond)  CLOG_IF(cond, INFO, OPENCOINEVO_LOG_CATEGORY)
#define OMWARN_IF(cond)  CLOG_IF(cond, WARNING, OPENCOINEVO_LOG_CATEGORY)
#define OMERROR_IF(cond) CLOG_IF(cond, ERROR, OPENCOINEVO_LOG_CATEGORY)


#endif // OM_LOG_H  
